### ISSUE TITLE
Are the original (not resized) images available for download?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [harsh19/spot-the-diff#2]
Are the original (not resized) images available for download?

**Comment by harsh19** [comment]
Hi Franck,
Thanks for showing interest in our work.
Sure, I will setup a link and share with you soon.

**Comment by Franck-Dernoncourt** [comment]
Great, thanks!

**Comment by harsh19** [comment]
Hi, 
You can download the data from bit.ly/spot_diff_data

**Comment by Franck-Dernoncourt** [comment]
Thanks very much!

**Comment by zijianchen98** [comment]
Dear Franck, Can you share the downloaded original images? The bit.ly/spot_diff_data is not reachable for us.

**Comment by zijianchen98** [comment]
> Thanks very much!

Dear Franck, Can you share the downloaded original images? The bit.ly/spot_diff_data is not reachable for us.
