### ISSUE TITLE
Error while loading obj

### ISSUE THREAD

**Issue by assaf86** [harsh19/spot-the-diff#3]
hi
I get an error while I'm trying to run this command:
`vals = pickle.load( open("../data/params_eps_20min_samples_9__allrectangles_corrected.obj","r") )`

tried to change it to "rb" but it still cause an error:
`UnpicklingError: the STRING opcode argument must be quoted` 

I'm working with python3  - any ideas how to solve?

**Comment by harsh19** [comment]
Hi,
Could you try with python 2 ?

**Comment by robinwkurtz** [comment]
@harsh19 thanks for your work on this! I think it in part could be very helpful for a project of mine.

I'm getting the same error as reported, if I switched to python 2.7 I then get an `EOFError` could you tell me which version you are running?

Thanks
